import { Outfit, Quicksand } from 'next/font/google';
import './global.css';

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  display: 'swap',
});

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
  display: 'swap',
});

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

import Navbar from '../components/Navbar';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${outfit.variable} ${quicksand.variable} scroll-smooth`}>
      <body className="font-sans antialiased mentara-bg">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
